// Mock data for resources
export const resourceCategories = [
  {
    id: 'health-tips',
    name: 'Health Tips',
    description: 'General health advice and wellness tips',
    icon: 'HeartIcon',
    color: 'bg-red-100 text-red-700',
  },
  {
    id: 'medical-guides',
    name: 'Medical Guides',
    description: 'Comprehensive guides on medical conditions',
    icon: 'DocumentTextIcon',
    color: 'bg-blue-100 text-blue-700',
  },
  {
    id: 'educational-videos',
    name: 'Educational Videos',
    description: 'Video content on health topics',
    icon: 'VideoCameraIcon',
    color: 'bg-purple-100 text-purple-700',
  },
  {
    id: 'news',
    name: 'Health News',
    description: 'Latest health news and updates',
    icon: 'NewspaperIcon',
    color: 'bg-green-100 text-green-700',
  },
  {
    id: 'research',
    name: 'Research Papers',
    description: 'Academic research and studies',
    icon: 'AcademicCapIcon',
    color: 'bg-yellow-100 text-yellow-700',
  },
];

export const mockResources = [
  {
    id: 1,
    title: 'Preventing Malaria: Essential Tips',
    category: 'health-tips',
    description: 'Learn how to protect yourself and your family from malaria with these essential prevention tips.',
    date: '2024-04-15',
    author: 'Dr. Ngono Marie',
    imageUrl: 'https://images.unsplash.com/photo-1584118624012-df056829fbd0?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    featured: true,
  },
  {
    id: 2,
    title: 'Understanding Diabetes Management',
    category: 'medical-guides',
    description: 'A comprehensive guide to managing diabetes, including diet, exercise, and medication.',
    date: '2024-04-10',
    author: 'Dr. Fon Peter',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    featured: false,
  },
  {
    id: 3,
    title: 'Nutrition for Pregnant Women',
    category: 'health-tips',
    description: 'Essential nutritional advice for expectant mothers to ensure a healthy pregnancy.',
    date: '2024-04-05',
    author: 'Dr. Biya Rose',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    featured: true,
  },
  {
    id: 4,
    title: 'COVID-19 Vaccination: What You Need to Know',
    category: 'medical-guides',
    description: 'Important information about COVID-19 vaccines, including efficacy, side effects, and availability.',
    date: '2024-03-28',
    author: 'Dr. Kamto James',
    imageUrl: 'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    featured: false,
  },
  {
    id: 5,
    title: 'Understanding Hypertension',
    category: 'educational-videos',
    description: 'A video guide explaining hypertension, its causes, symptoms, and management strategies.',
    date: '2024-03-20',
    author: 'Dr. Ngono Marie',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    featured: false,
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  },
  {
    id: 6,
    title: 'New Breakthrough in Malaria Treatment',
    category: 'news',
    description: 'Recent research shows promising results for a new malaria treatment approach.',
    date: '2024-03-15',
    author: 'Health Service Directory Team',
    imageUrl: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    featured: false,
  },
  {
    id: 7,
    title: 'Effects of Climate Change on Public Health in Cameroon',
    category: 'research',
    description: 'Academic research on how climate change is affecting public health outcomes in Cameroon.',
    date: '2024-03-10',
    author: 'Dr. Fon Peter',
    imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    featured: false,
  },
  {
    id: 8,
    title: 'Healthy Eating on a Budget',
    category: 'health-tips',
    description: 'Practical tips for maintaining a nutritious diet while managing costs.',
    date: '2024-03-05',
    author: 'Nutritionist Sarah Nkeng',
    imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    featured: false,
  },
]; 